CREATE TABLE registration (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nameinst VARCHAR(255) NOT NULL,
    instadd VARCHAR(255) NOT NULL,
    instemail VARCHAR(255) NOT NULL,
    principal VARCHAR(255) NOT NULL,
    principalno VARCHAR(15) NOT NULL,
    teamname VARCHAR(255) NOT NULL,
    mentorname VARCHAR(255) NOT NULL,
    mentorno VARCHAR(15),
    mentorquali VARCHAR(255),
    mentoradhar VARCHAR(255),
    stdfirstna VARCHAR(255),
    stdfirstph VARCHAR(255),
    stdagefirst INT,
    stddivfirst VARCHAR(255),
    stdsecna VARCHAR(255),
    stdsecph VARCHAR(255),
    stdagesec INT,
    stddivsec VARCHAR(255),
    stdthridna VARCHAR(255),
    stdthridph VARCHAR(255),
    stdagethrid INT,
    stddivthrid VARCHAR(255),
    stdfourtna VARCHAR(255),
    stdfourtph VARCHAR(255),
    stdagefourt INT,
    stddivfourt VARCHAR(255),
    stdfifthna VARCHAR(255),
    stdfifthph VARCHAR(255),
    stdagefifth INT,
    stddivfifth VARCHAR(255),
    amount INT
);